CREATE TABLE Binay_campaigndonors (
    JEJOMAR_BINAY_S_2010_CAMPAIGN_DONORS VARCHAR(44) CHARACTER SET utf8,
    DONATION_IN_PESO INT,
    TYPE_OF_DONATION VARCHAR(4) CHARACTER SET utf8
);
INSERT INTO Binay_campaigndonors VALUES ('Zshornack, Darlene Webb',10000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Buencamino, Anne Lorraine',7500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Victor',5000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tiu, James',5000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lagdameo, Enrique B.',5000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Valdepenas, Victor B.',5000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Limlingan, Victor S.',3000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Padilla, Eillene A.',3000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('2355 Property Holding Company',2500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rams House of Wine Inc.',2500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ritra Phils. Inc.',2500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Adriano, Magleo V.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Banguis, Tomas Jr.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Benavidez, Socorro M.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Benavidez, Victor',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Mar-Len Abigail S.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Buenviaje, Rene Antonio',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Clarino, Emmanuel',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Copuyoc, Mario L.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Ocampo, Emmanuel V. / De Ocampo, Pilar H.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Ocampo, Ma. Rosela H.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Alejandro',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Vincent Paul',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gimena, Lea',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lainez, Enrico M.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Laurel, Bernardina',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lee, Mary Ann R.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Licauco, Sally',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Julie L.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lucero, Roy Eduardo T.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Macatangay, Janine',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mañalac, Eduardo V.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mangosing, Emmanuel T.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manto, Melinda G.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mara, Jose Dante P.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Paredes, Luis Alvarez',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ramos, Mildred',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Remo, Rico Gabriel Chavez',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Maria U.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Roman Felipe S.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Toribio III',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Toribio Jr.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Dominador Jr. H.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Ruben',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sebastian, Jose Juel M.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tacandong, Protacio T.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Viray, Raoul B.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Espino, Cirilo V.',2000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cantre, Francisco C.',1500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Elefan, Emmanuel S.',1500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Baterina, Christopher R.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bayon, Francis Edward Banacia',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bernardino, Ma. Bella C.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Caballa, Wilredo',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Campos, Erlinda',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cualing, Josefino D.M.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Del Monte, Roberto C.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Delos Santos, Rome Jr. D.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Escano, Antonio S.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Evangelista, Michael C.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Alex',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guevara, Daniel S.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Iñigo, Marinele M.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Julian, Shermaine M.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Libot, Arturo F.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Malaca, Christopper T.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manuel, Gideon S.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Maravilla, Ma. Cynthia V.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Marcelo, Ferdinand',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ng, John James D.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Palomo, Katrina Teresa T.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pastrana, Quintin',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pe, Dianne Kathleen P.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pia, Jessehan P.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Po, Jose Marie G.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rosales, Micaela A.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sierra, Emmanuel C.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Simbol, Peter Paul',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Siy-Yap, Betty C.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tan, Aileen M.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Venida, Danilo',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Yague, Keith J.',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gloez, Paul Alexis',1000000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guttierez, Augusto T.',700000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sanchez, Arsenio Jr. A.',600000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ang, Antonio R.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Atienza, Victor J.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bachoco, Bennette D.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bayot, Chinnie R.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bembo Estelloso R.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cabacungan, Elinore',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cabrera, Angelica DP.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cadavez, Dyan Michelle',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Castañeda, August',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Castro, Carmencita T.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Chua, Carl',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cobarrubin, Domingo Meneses',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Corpuz, Edna',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dabarag, Marlon A.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dioso, Julie O.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Divino, Anthony Glenn O.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Domingo, Faustino Rene C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Duque, Cesar',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Evangelista, Eduardo B.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Exconde, Leandre M.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Ethelwoldo E.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Lucio Waldo Ausejo',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernando, Belinda B.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fulay, Rence Tolud',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Galvez, Juanito',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Garde, Sahle B.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Garibay, Joseph E.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gilbuena, Francisco Roel Gilbuena',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Hu, Antonio C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ignacio, Rodel Velasquez',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Jamero, Rogelio II D.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Javier, Jeffrey M.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Landrito, Carlota E.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lapuz, Melino Jr. S.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lozada, Manuel',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lucino, Jerome S.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lugartos, Rodolfo Jr. T.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Macatangay, Winnie C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Maglaque, Eduardo C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Maligaya, Norberto G.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mamuric, Jose Amado',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manuel, Ivy V.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manzon, Danilo',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Marinas, Felix Jr. J.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Merina, Jameson John V.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Monzon, Alfredo Jr. R.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Nagano, Mae Grace T.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ofredo, Marina A.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Orallo, Wilfredo C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Orcullo, Christopher L.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Orsine, Jinky A.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pamatian, Rolly T.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Peralta, Feliza A.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Po, Joaquin Ernesto L.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Poblete, Ricardo Jr. G.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ramos, Dominador Jr. I.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Retugal, Paulano Ariane T.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Jorge C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Josefina J.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes-Arcenas, Haydee M.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sabio, Felicidad M.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('San Jose, Gene Eric',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santico, Renato R.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Arnel L.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sapalo, Joseph Anthony C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Serrano, Eleuterio T.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sigua, Girlie',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sinsuat, Datu Omar S.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sison Tin, Marie Frances Carlota',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Smith, Victoria C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sunga, Mary Ann C.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tan, Alnette',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tria, Genaro Jr.',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Vinzon, Rafael',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Yu, Anna Lisa',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Hernandez, Jose Rafael',500000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Castrillo, Jose Paulo B.',300000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Dios, Maria Martha',300000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gregorio, Augusto Jr.',300000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Edmer',300000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lopez, Hirene',300000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Monis, Arnel',300000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Buensuceso, Jose',250000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fuster, Rebecca Penafuerte',250000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tuazon, Kennedy B.',250000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Agregado, Wilhelmino',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Alcantara, Marie V.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Alfonso, Rochelle S.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Almendral, Doroteo M.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Andrada, Elena Q.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Angeles, Jose Maria',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Angeles, Ma. Luisa Eleazar',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Angeles, Margarita Lara E.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Aquino, Ma. Sharae G.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Baday, Lindy',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bantayan, Joel M.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Barrera, Anthony',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bato, Lita',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bechez, Randy Jr.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Belen, Jose',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bellosillo, Jaime',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Boncales, Danilo',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bustos, Felixberto',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Caballa, Wesley',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dador, Imelda',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dancel, Mario',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dauz, Alexander',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Vega, Norieva D.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Del Rosario, Teresita N.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dela Cruz, Arnolfo',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dela Cruz-Ladlad, Amalia Amy',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dula, Ella',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dy, Imee',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Febrer, Pamela J.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Galela, Wilma P.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guevarra, Eduardo P.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Hernan, Pasol G.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Jacobe, Christian',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Javier, Carmelo',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Joel, Delfin',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ladlad, Anthony Pinca',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Librado, Vic',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lorenzo, Jennifer',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Macahilo, Charina',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Macahilo, Edrie R.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Macahilo, Reygan',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Macahilo, Reynaldo',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mallete-Soriao, Fe',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mangahas, Ma. Katherina C.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mangro, Kathrina Domiquee O.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Marcelo, Genaro R.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mariano, Nathaniel',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Melo, Eleuterio L.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Merin, Robert Ceasar',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Minay, Rovante',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Miranda, Lauro S.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Nanas, Dino Dator',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Nicolas, Krisanto Karlo E.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ocampo, Ferdinand',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Osejo, Vivian',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pacaro, Leodilito G.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pido, Chito A.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pizarro, Ian V.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Raganit, Vladimir Eric',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rimando, Mark Anthony',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rodriguez, Gilbert',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Romero, Charlie Cabasal',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sanchez, Karen P.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Serrano, Maria Cristina F.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sibulo, Ma. Carla D.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Simosa, Josefina T.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Suplente, Nancy G.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tabla, Vicente',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tablando, Fe',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tamor, Leonito Jr. D.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Valderrama, Edmund T.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Yu, Anita A.',200000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Conde, Cristina',150000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Alcantara, Eliseo Jr.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Andrade, Wilredo P.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Astete, Elsie B.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bautista, Michael S.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bichara, Miguel',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Angeline',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, George',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Hope',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Joselito V B.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Leonita',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Virgilio',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay-Agbay, Fe',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bongato, Rodolfo',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Budhrani, Deepak',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Canizares, Morena S.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Caraan, Severino G.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Co, Renato',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Comia, Azucena',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cristobal, Anthony',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cuasay, Celia',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cuosay, Catalina',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Delos Reyes, Mary Grace',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Delos Reyes, Nicasio E.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Devara, Grace Binay',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dizon, Rosemarie',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Garcia, Luis Claudio G.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gatchalian, Josephine',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guevarra, Aurora Reyes',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Herrera, Luisa',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Jorvina, Christy',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lalandale, Angelo',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Limlingan, Victor Jr.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Luna, Norma Cruz',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Malazarte, Ma. Helen Lebitania',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Marasigan, Fernando',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mayoralgo, Nicanor M.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mendoza, Nenita C.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mercado, Gadburt',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mijares, Roberto',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Monteverde, Ronald Stephen V.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Morillo, Alberto P.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Munda, Romeo L.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ocampo, Francisco De Vega',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ordillas, Miles',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Osario, Boyet',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pena, Louie',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pozon, Vincent',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ramboyong, Armin',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Estelita',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Priscila',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rimonte, Raquel',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rufino, Ma. Teresa P.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Samson, Wilbar',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santiago, Maria',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Richard C.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sison, Paulo M.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Suarez, Elizabeth',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Suarez, Jason B.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tandang, Julita',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Uy, Joseph Jerome L.',100000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sycip, Claudine',80000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Abadilla, Monina',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Abaya, Norberto R.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Abregaudit-Asunio, Mabel',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Agno, Merlinda P.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Alcantara, Eliseo V.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Alcanzare, Ernesto A.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Angeles, Maria Lourdes Nancy Binay',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Asinas, Michael Alvin',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bahinting, Sol Miñoza',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Banes, Leilani',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Barlis, Mindanilla',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Beleno, Arlene',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Joselito II O.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Borja, Enrique',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cagisao, Belgina S.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Candelaria, Christine',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Co, Chester Allan T.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Co, Michelle Chang',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('David, Alfredo B.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Masilungan, Angelina',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Del Rosario, Hannah Piramide',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dela Cruz, Alexander B.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dizaon, Elpidio Jay Jr. S.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Eleazar, Geraldo G.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Faronillo, Antonio Ramon Jr.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Elias A.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fuster, Getulio III P.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gan, William S.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gonzalez, Ronaldo S.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guerrero, Joselito Monti',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gutierrez, Joselito P.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Jacinto, Michael',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Licerio, Marcial P.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Arvin',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Carolyn',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Cecilio III P.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Emerson O.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Jennifer K.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lim, Mary Ann O.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Liwag, Gerardo',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lobrio, Victor G.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lopez, Constante Jr.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Luna, Joseph Y.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Luna, Naressa',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manalo, Norma Ramos',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manalo, Rodrigo',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Masiglat, Florence',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Meneses, Ernesto N.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mitchell, Lucita W.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Nabong, Teodora Jr. A.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ng, Christine Lim',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Panganiban, Raymund',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pascua, Elsie',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Perez, Joana E.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Punzalan, Gemma A.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ramos, Shirlie C.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Eugenio M.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, Sharon',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rodos, Jose R.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Roxas, Ma. Linda',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sedillo, Fedelina Quano',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Serra, Maria Josefina B.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sienes, Rodolfo',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sunga, Nerissa Marcelo',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sycip, Albert L.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Taccag, Ma. Rhodora G.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tan, Mary Hulsuan',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tuazon, Benjamin',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Velasco, Bernie B.',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ventura, Paolo',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Yupiah, Chesteralan Tan',50000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dequina, Consuelo D.',35000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ocampo, Mary Candy Rosalie',35000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Celina S.',30000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Evangelista, Leonardo C.',30000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mendoza, Marino T.',30000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Viesca, Sheila',25000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Aguilar, Reynaldo',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Aguirre, Arturo',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Angeles, Jose Benjamin',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Arenas, Ruby V.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Barola, Neptalie Boksa',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Basañez, Leonilo G.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cinco, Desiree D.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dasco, John P.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dela Pena, Dominador N.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Delos Santos, Jovita',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Espino, Tessa Mar L.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fancubilla-Pontino, Thetz',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Franco, Ronnie V.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gardiola, Anthony',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gelisan, Leo Almeda',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Goleco, Joyce S.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Juan, Enrique Luis P.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lanip, Juliana M.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Legaspi, Grace R.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lucero, Gregorio III A.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manguiat, Silvina',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manzala, Jaime Jr. M.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Oblanca, Pacifico Jr. T.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Raposas, Marco',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('San Juan, Marcelino F.',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Serra, Vicente',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Vinarao, Jonas',20000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Elag, Josefina P.',15000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ventura, Anna L.',15000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Agregado, Alvin G.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Atienza Estelita',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Felomena Belbez',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Marilyn D.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Norbeta E.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Binay, Regelyn Evangelista',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bocaoco, Ricky A.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Borba, Elmo',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Buen, Cynthia C.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Camacho, Prince Oliver P.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Campomanes, Mary Grace',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Canlobo, Angela D.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cimaves, Lily',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Crystal, Lily H.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dela Cruz, John',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Irum, Betzaida H.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Limlingan, Gerado Castaneda',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lirio, Donna A.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Lorenzo, Melanie M.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manahan, Remigio Jr. M.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Manalili, Benjie',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Micosa, Nemencia M.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Morales, Gloria R.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mosqueda, Celestina S.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Nolasco, Mary Ann',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pietro, Sol Rosalie O.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Punzalan, Maria Aurora C.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Quizon, Melisa P.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Reyes, May Lyn J.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sanchez, Marissa G.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Solomon, Domingo Jr. P.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Solomon, Eric',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Umalis, Marvie V.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Villarba, Ernesto Odilon III H.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Villarta, Ana S.',10000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Escatoto, Arnold',7500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Arpon, Jonathan E.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Asadon, Arnold B.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bajalan, Ronald D.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Baluyot, Elvira P.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Brinosa, Minerva',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cabral, Reynaldo H.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Canlas, Rowell T.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Guzman, Michael Rueben S.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Guzman, Oliver Ruel S.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dollente, Ma. Lourdes Y.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Estrelladas, Welsie',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gadas, Francisco Jr. L.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Grey, Rutchel L.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Jacob, Hector',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Jarmin, Felix',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Javier, Maria Beatriz C.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Largueza, Wilane C.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mariano, Chanda',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mendoza, Nestor M.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Paglinawan, Noel L.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Panaligan, Medy',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Portollano, Bernadette',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Portollano, Percelita G.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Glenn Michael',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Maria Jenlyn',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sison, Rizabele T.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ventura, Agnes L.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ventura, Diostin Justino S.',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Yaoto, Rosemarie',5000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ferrer, Rosemarie',4000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Secretario, Patricia',4000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Anasco, Frank M.',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Anasco, Marilou M.',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cruz, Rose',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Din, Marjorie C.',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gulla, Edwin R.',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Moreno, Angel',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Portollano, Helen',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Portollano, Jose L.',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Vivero, Enrique B.',3000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bartolome, Maribel B.',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cortez, Joseph Rommel V.',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Dianopra, Erma T.',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guevarra, Analiza B.',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mesa, Constancia',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sanopao, Ronaldo',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sanopao, Ronelo O.',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Trinidad, Karen Reyes',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Zulueta, Mary Jane',2500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Amboyao, Joseph C.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Apostol, John Q.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Camangian, Ilalo Jr.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Cantos, Gerez Delante',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Capino, Jonathan',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Casas, Jocelyn',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Sena, Marissa Elaga',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Domingo, Edward Jay R.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Esplana, Silwyn M.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fabregas, Honeylyn',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fernandez, Carlito D.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Forte, Leonardo C.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Gamueta, Jopether Dela Cruz',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Mendoza, Sharon',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pidot, Bernardo C.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Ragadio, Dennis Alaras',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rivera, Rosemarie',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rodriguez, Arnold G.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Romero, Grace Ann A.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sabenorio, Jimmy S.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sambok, Marichoe Berto',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('San Gregorio, Michael',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Arnel Miguelito I.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sayat, Dennis C.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Segundo, Corazon',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Villareal, Bernard',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Vinoya, Wilson C.',2000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Malinao, Charisa I.',1500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Abundo, Jojimbo',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Aguinaldo, Aldrin A.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Aguinaldo, Ariel',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Alvarez, Rebecca S.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Baleares, Marie Claire Michelle S.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Betwarto, Teresita',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Calosing, Liza T.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Canonigo, Rowena A.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Coroza, Lourdes B.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Coroza, Noel John',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Coroza, Wilfredo L.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('De Guzman, Marilou Manuel',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Evangelista, Randy',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Guy-Joco, Florentino Abando',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Hilario, Edgardo D.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Malanday, Jenie',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Marfil, Liza',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Martinez, Benedict B.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Miranda, Ma. Buenaflor',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Nalang, Gritchen B.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pellas, Mercedita S.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rabin, Ronaldo',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Rellin, Jocelyn E.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Santos, Petronilo B.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sevilla, Evangeline V.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Soliven, Fernando Jr. U.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Tinioso, Marlon S.',1000,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Arevalo, Jacqueline',500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Bulahan, Eugene A.',500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Fajardo, Mitchie C.',500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Pidot, Analyn C.',500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('Sequito, Leah May',500,'Cash');
INSERT INTO Binay_campaigndonors VALUES ('TOTAL',228430000,NULL);
