CREATE TABLE soi_4 (
    list INT,
    list_candidate_id INT,
    list_created_at DATETIME,
    list_id INT,
    list_issue_id INT,
    list_quote VARCHAR(843) CHARACTER SET utf8,
    list_source VARCHAR(139) CHARACTER SET utf8,
    list_summary VARCHAR(14) CHARACTER SET utf8,
    list_updated_at DATETIME
);
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',64,1,'''''In the first 100 days in office, we would prompt Congress for bills to be passed with dispatch. First is the Freedom of Information Bill, which I have sponsored and debated on in the Senate.''''','http://newsinfo.inquirer.net/734850/4-presidentiables-on-foi-cha-cha-corruption-tax-reform','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',65,2,'''''Any move towards federalism should be preceded by strengthening local government institutions and urgently passing the FOI and Anti-Dynasty Bills... Studies have shown that there is a correlation between dynastic rule and mal-development.''''','http://www.tempo.com.ph/2015/10/06/foi-anti-dynasty-laws-first-before-federalism-poe-says/','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',66,3,'''''Mas alam ng tao kung ano ang kailangan nila at mas may karapatan kayong gastusin ang inyong pinaghirapan.''''','http://www.gmanetwork.com/news/story/537177/news/nation/grace-poe-vows-lower-income-tax-faster-internet-passage-of-foi-law','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',67,4,'''''Congress must be given the opportunity first to come up with a constitutional version of the BBL.''''','http://dzmm.abs-cbnnews.com/news/National/Constitutional_version_ng_BBL,_dapat_hintayin_bago_mag-peace_summit_-_Poe.html','No Clear Stand','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',68,5,'''''Atin ang West Philippine Sea. At dapat lang na huwag nating bitiwan o pabayaan ang gamit ang mapayapang paraan. Alinsunod dito, palakasin din natin ang Coast Guard at Sandatahang Lakas para hindi tayo kinaya-kaya lang ng ibang bansa.''''','http://www.philstar.com/headlines/2015/09/16/1500513/full-text-grace-poes-presidential-bid-announcement','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',69,6,'''''I am open to economic charter change. I am open to changes in our economic provisions... (so long as these do not) cross over to certain democratic political safeguards that we already have in our Constitution.''''','http://www.interaksyon.com/business/120722/poe-open-to-economic-chacha','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',70,7,'''''In our society heterosexuality which is generally accepted as the normal, moral and only sexuality legitimizes and supports social and cultural prejudices and discrimination against LGBT persons. Legal recognition and protection of the rights of LGBT persons will make more visible LGBT-specific violations and discrimination. It will affirm also that LGBT persons have equal rights, freedoms and status as other people.'''' (Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',71,8,'''''If he (FPJ) were alive today, and if he witnessed the programs of the President, he would agree also with the Conditional Cash Transfer. Not because he would like us to have a dependent citizenry, but because, well, let''s say you have five children, and three of your children are doing well, but two of them need a little bit more of a push. They need more capital, they need more support, at least when they first start out.''''','http://lifestyle.asiandragonmagazine.com/?p=297','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',72,9,'QUALIFIED NO</b>''''Let me qualify my answer. I am opposed to labor-only contracting. This is what our law prohibits. This is distinguished from legitimate contracting in the context of outsourcing, which is recognized as an economic tool (e.g., to expand business, streamline operations, and promote more inclusive value chains). I oppose the abusive practice of companies that hire workers for a period not exceeding five months in order to circumvent the law. This kind of perpetual contractualization results in perpetual insecurity of tenure. It contributes to poverty, is unfair and unjust.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'No','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',73,10,'''''Kung bibigyan ng pagkakataon, ako po ay di sang-ayon sa divorce. Lalo na ngayon, dahil sa ating kultura at dahil din sa ating mga paniniwala.''''','https://www.youtube.com/watch?v=Oi7IINcDK5w','No','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',74,11,'''''A hero''s burial would be tantamount to negating the experiences of the thousands of victims of human rights violations and Martial Law atrocities. It is more than just laying a body to rest, but what it symbolizes. His is not the glory demanded of heroes. Indeed he was a former soldier, a guerilla fighter during World War II, and a president of the republic. However, he died while on exile, he ran away from a people that had revolted against him, he did not account for millions of state funds that were plundered. He not only squandered upwards of $5-10 billion, but most of all, he did not answer for the human rights violations attributed to his autocratic regime.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'No','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',75,12,'''''Land is a very scarce resource so there is an urgent need to pass a national land use law, which has been pending in Congress for more than two decades now. This proposed measure will ensure a rational, holistic, and just allocation, utilization, management and development of the country''s land resources to ensure their optimum use, consistent with the principle of sustainable development.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',76,13,'''''When RA 10368 was passed into law in 2013, it provided for the reparation and recognition of victims of human rights violations during the Marcos regime. It is therefore, official State policy ''to recognize the heroism and sacrifices of all Filipinos who were victims of summary execution, torture, enforced or involuntary disappearance and other gross human rights violations committed during the regime of former President Ferdinand E. Marcos... and restore the victims'' honor and dignity.'' Furthermore, under the law, the State acknowledged its ''moral and legal obligation to recognize and/or provide reparation to said victims and/or their families for the deaths, injuries, sufferings, deprivations and damages they suffered under the Marcos regime'' ''''.(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',77,14,'''''We have many talented and skilled Filipinos, who could certainly be an asset to nation-building. We need them here, but we lose them to other countries. Hindi tayo ang nakikinabang sa galing at husay nila. Our goal is to create enough decent and fulfilling jobs here in the Philippines, which provide workers with ample incomes so that Filipinos need not go abroad to work, (and be separated from their families). However, while overseas employment must not be a necessity but merely an option for our workers, those who still opt to leave should be given ample protection, information and legal services by the DFA, DOLE and other relevant agencies.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'No','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',78,15,'''''My administration will enforce a zero-tolerance policy on corruption. We will approach the full spectrum of corruption cases, whether high or low level, with equal conviction under strict, egalitarian principles. We strongly oppose all forms of corruption, including graft, bribery, fraud, extortion, favoritism and nepotism.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',79,16,'''''I support the right of two consenting adults to contract civil marriage, regardless of their sex. All persons are guaranteed equality in their rights. Human rights accrue to them from birth. Our Constitution mandates the State to guarantee full respect for human rights. Our laws cannot discriminate against persons because of their sexual orientation and gender identity.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',80,17,'''''I like the K to 12. I think the mother tongue approach is good, the focus on early childhood is there. My real dream is to have a free lunch program in public elementary schools.''''','http://lifestyle.asiandragonmagazine.com/2015/09/03/facing-grace-grace-poe-talks-about-the-cct-the-k-12-program-and-her-future-in-politics/','Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',81,18,'QUALIFIED YES</b>''''CARP was the centerpiece of the 1987 Constitution. Decades of exploitation and social injustice called for a new policy based on awarding land to the tiller. I intend to complete this program because I believe this will address the inequitable distribution of wealth and is therefore key to alleviating poverty in the rural areas. However, we must end the land acquisition and distribution soonest, and not go beyond the lands that were covered by DAR prior to the expiry of CARPER in 2014. The significant adverse effect of CARP on agricultural investment was primarily due to the uncertainty it caused with lands yet to be covered by DAR. This uncertainty must end as soon as possible, to revive the rural land markets and stimulate renewed agricultural investment.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',82,19,'''''Given the unfinished peace processes and delayed delivery of justice, it is imperative that government act swiftly and decisively to show our commitment to peace and development. Conflict must be resolved through an inclusive, sensitive, and effective political settlement which will build the trust and the peace between parties, and enjoin insurgents to constructively engage with mainstream society for their desired reforms.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'Yes','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',83,20,'''''Leave it to the courts to decide.''''(Email reply to InterAksyon''s Sept. 2015 questions)</b>',NULL,'No Clear Stand','2016-03-31 19:17:14');
INSERT INTO soi_4 VALUES (NULL,4,'2016-03-31 19:17:14',84,21,'''''Hindi lang ang Pangulo ang may pananagutan diyan. Lahat ng tumanggap niyan ay may pananagutan sa bayan at kailangan nila maipakita kung saan nila ginastos ''yan.''''','http://www.gmanetwork.com/news/story/369234/news/nation/grace-poe-dares-aquino-fellow-senators-to-account-for-dap-funds','Yes','2016-03-31 19:17:14');
