CREATE TABLE soi_marcos (
    list INT,
    list_candidate_id INT,
    list_created_at DATETIME,
    list_id INT,
    list_issue_id INT,
    list_quote VARCHAR(849) CHARACTER SET utf8,
    list_source VARCHAR(159) CHARACTER SET utf8,
    list_summary VARCHAR(14) CHARACTER SET utf8,
    list_updated_at DATETIME
);
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',169,1,'''''The FOI is a tool that encourages government to carry out its mandates honestly, competently, and with due regard to all stakeholders in critical issues and challenges facing the nation.''''','https://www.senate.gov.ph/press_release/2015/0729_marcos2.asp','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',170,2,'''''It''s not something that only happens in the Philippines. It''s something that we see in every country... having the son, having the daughter, or having the nephew of a previously elected official [run for public office] is not necessarily a bad thing.''''','http://kickerdaily.com/political-dynasties-are-normal-says-bongbong-marcos/','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',171,3,'''''The tendency of this government is to collect and collect. It can''t be ''tax pa more'' all the time. What is more important is ''public service pa more.'' I fully support the lowering of income tax. What''s the rationale behind collecting too much tax when the government doesn''t know when and where to spend it?''''','http://www.bongbongmarcos.com/news/post/sen-bongbong-asks-why-tax-people-heavily-when-services-come-slowly/','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',172,4,'''''The problem is-and this is a big problem-it turned out in our hearings in the Senate that many of the provisions of the draft BBL are unconstitutional.''''','http://www.journal.com.ph/news/top-stories/draft-bbl-violates-charter-marcos','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',173,5,'''''China opened the door and we shut it. The Chinese said let''s talk and we snubbed them. It''s like the Philippine government itself is encouraging China to take and maintain an unbending stance on the issue. So talk, and tell them: we are not happy with what you are doing and we do not agree with what you are doing. But the next thing you say is: how do we fix this.''''','http://www.philstar.com:8080/headlines/2015/07/09/1475020/bongbong-bilateral-talks-china-opened-door-we-shut-it
','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',174,6,'''''Asked in 2012 what were his thoughts about Charter change, Bongbong Marcos said, ''I was very, very gratified to hear the Senate President say that (Cha-cha is a priority in the Senate), because talaga namang maliwanag na may maraming kailangang ayusin, palitan... Kung talagang matutupad, economic provisions lamang ang pag-uusapan.'' ''''','http://www.bongbongmarcos.com/news/post/transcript-of- interview-of-senator-bongbong-marcos-during-the-opening-of-the-3rd-regular-session-of-the-15th-congress/','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',175,7,'''''For me, the law should treat the people equally whoever you are. Whatever or whoever you want, the state should allow it because it is your choice. We should no longer discuss if it is conventional or not, as long as you are a Filipino, you should be treated fairly.''''','http://lifestyle.inquirer.net/207936/love-not-gender-defines-marriage-says-senator-marcos','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',176,8,'''''There is no element of balanced equity in the present CCT program where the funds should have come from the rich sector and transferred to the poorest of the poor. Then, of course, there is the potential for political abuse.''''','http://www.philstar.com/headlines/2014/08/06/1354565/marcos-aquinos-cct-failure','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',177,9,'''''(W)hen we do get hired, we shall encounter during actual employment the realities of minimum wage and low salaries, the prevalent ''contractualization'' of labor... and layoffs, even abusive employers... Huwag tayong papayag na masupil at mapigilan ng mga ito ang ating mga pangarap.''''','http://www.bongbongmarcos.com/news/post/speech-at-the-43rd-commencement-exercises-of-rizal-technological-university-rtu/','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',178,10,'''''He said there was no reason for him to support the divorce legalization. No. I love my wife. I do not want to divorce her.''''','http://www.interaksyon.com/article/107605/senators-not-in-favor-of-legalizing-divorce-in-the-philippines','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',179,11,'''''The position of the family has not changed from the very start. It is his right as a soldier, a decorated soldier and a veteran to be buried in the Libingan ng [mga] Bayani. It is his right as a President, the longest serving President to be buried at the Libingan ng [mga] Bayani. We feel that it is his right.''''  <b>(Interview during Bilang Pilipino ''Happy Hour'' segment at TV5 Media Center in Mandaluyong City, Jan. 29, 2016)</b>','https://soundcloud.com/interaksyon/marcos-buriallibinganngbayani/s-2Xuox','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',180,12,'''''Guided by the principle that the use of land bears a social function and that all economic agents shall contribute to the common good, landowners, land tenure holders, in the case of forestlands, be it an individual, communal, corporate or group shall be held responsible for developing and conserving their lands thereby making their lands, productive and supportive of environmental stability.''''','http://www.bongbongmarcos.com/wp-content/uploads/senate-bill/senate-bill-no-3091-national-land-use-act-of-the-philippines/SBN-3091.pdf','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',181,13,'(On the ill-gotten wealth cases) ''''Let them go to court. These things will take a life of their own.''''','https://www.youtube.com/watch?v=veazV0FmTVc','No clear stand','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',182,14,'''''I think the long term aspiration should be to bring them back. There is a social cost to having families separated. There is a social cost to that. And I think it is also a lost opportunity for us because all their hard work, all their skills, all their talent should be applied to the development of the Philippines. Dapat dito sila at tinatrabaho nila, pagtyatyagaan nila para makatulong dito sa ating bansa. Now, not to say that the 24 billion, 25 billion (peso) remittance is nothing. But I think we would be better served if we we''re able to provide employment to our people.'''' <b>(Interview during Bilang Pilipino ''Happy Hour'' segment at TV5 Media Center in Mandaluyong City, Jan. 29, 2016)</b>','https://soundcloud.com/interaksyon/marcos-laborexport','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',183,15,'''''I think the public wants closure on this issue. They want to know the score. If they are guilty, punish them. If they are not, set them free.''''','http://www.senate.gov.ph/press_release/2014/0626_marcos1.asp','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',184,16,'''''There is nothing wrong,'''' Bongbong Marcos said, ''''if the state would officially acknowledge that there is part of this society that wants same sex marriage [to be legalized].''''','http://lifestyle.inquirer.net/207936/love-not-gender-defines-marriage-says-senator-marcos','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',185,17,'''''I''m not sure that just putting two extra years will improve the educational attainment of our students. What we should do is strengthen the educational system that we have. Marami pang questions and I think we have to rethink through the problems of K-12.''''','http://www.senate.gov.ph/press_release/2015/0718_marcos1.asp','No','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',186,18,'''''I always thought the agrarian reform program was finished because the rice and corn, nag-umpisa ''yan. Natapos na ''yan. Now, that''s why I think because hindi maliwanag what the intention is of the extended comprehensive agrarian reform program, kaya nagkakaproblema sa implementation.<br/><br/>So, I think we should dial it back and look again to see what the original principles... were... If I remember, it''s in P.D. 27, the land reform na pinamana ng aking Dad, ng aking father. And as far as I could tell, that was already completed, lands of rice and corn. Ang dapat siguro nating tingnan ngayon is the urban land reform, housing... Nagkakaproblema because it''s not clear what we are intending to do. We have to rethink. Ano ba talaga gusto nating mangyari hanggang ngayon hindi natin alam.'''' <b>(Interview with InterAksyon, Jan. 29, 2016)</b>','https://soundcloud.com/interaksyon/marcos-agrarianreform/s-sf9s0','No Clear Stand','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',187,19,NULL,NULL,NULL,'2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',188,20,'''''Hindi ba sinabi sa UN na that it is a human rights violation, on the way she has been detained? So, I think we should understand that. We should recognize that... I was not an ally of GMA in her time as president but I think that this is already cruel and unusual punishment.<br/><br/>Lahat ng kasama niya sa kaso... tapos na ang kaso nila. Na-acquit na. Siya na lang ang naiwan. I don''t know if this is a legal. This is something again may bahid ng pulitika... Hindi naman siya tatakas eh. What are we worried about? She''s not going to escape. She''s not good to run anyway. She''s not well. So, what is the harm? I do not see the harm in her going home.'''' <b>(Interview during Bilang Pilipino ''Happy Hour'' segment at TV5 Media Center in Mandaluyong City, Jan. 29, 2016)</b>','https://soundcloud.com/interaksyon/marcos-arroyobailgrant/s-qOaeK','Yes','2016-03-31 19:17:14');
INSERT INTO soi_marcos VALUES (NULL,10,'2016-03-31 19:17:14',189,21,'''''It''s not only labag sa batas, it''s labag sa Saligang Batas. It is unconstitutional so it''s a clear violation.'''' <b>(Interview with InterAksyon, Jan. 29, 2016)</b>','https://soundcloud.com/interaksyon/marcos-dap/s-rG3s5','Yes','2016-03-31 19:17:14');
