CREATE TABLE VPEscudero_campaigndonors (
    CAMPAIGN_CONTRIBUTORS VARCHAR(43) CHARACTER SET utf8,
    AMOUNT INT,
    TYPE_OF_DONATION VARCHAR(28) CHARACTER SET utf8
);
INSERT INTO VPEscudero_campaigndonors VALUES ('Frabelle Corporation',10000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Manalansan, Reynaldo Nuqui',10000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Acuzar, Jose Rizalino Larion',10000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('BA Securities, Inc.',5000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Villanueva, Myla Crespo',5000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Reyes, Adolfo II Zulueta',4000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Taojo, Noe B.',4000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Arapoc, Stephen A.',3000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Flores, Danny Lim',3000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Galang, Ferdinand',3000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Tactay, Angel',3000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Tesado, Josue',3000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Fausto, Andre Pablo Geslani',2000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Llamas, Antonio V.',2000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Madrid, Melvin',2000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Philippine Union Realty Development Corp.',2000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Yu, Alicia S.',2000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Antonio, Roberto V.',1250000,'Streamers, Posters, Stickers');
INSERT INTO VPEscudero_campaigndonors VALUES ('Buyco, Purisimo S.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Cordero-Tan, Fides Cajulao',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Diego, Felipe Roxas',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Dogillo, Anthony',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Esguerra, Ramon Santonil',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Gutierrez, Santiago',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Jowood Industries',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Laogan, Daniel Cheng Jr.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Lara, Roberto Jota/ Lara, Irma Delos Santos',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Lucila, Roberto Rafael V.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Marasigan, Diosdado Bama',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Olvina, Deogracias Ramon Jr. R.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Parel, Roberto O.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Prado, Tomas N.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Sibulaya, Victoria R.',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Unero, Agaton Teodoro Oliver',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Villarica, Henry Resurreccion',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Yap, Leoncio',1000000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Ignacio, Raymund Aquino',850000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Chua, George Tiu',500000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Esguerra, Jose Exequiel Alfajora',500000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Ibuyan, Benedict Julius Fantastico',500000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Lomibao, Robel C.',500000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Reyes, Pastor Miro Jr.',500000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Yalung, Charlie C.',500000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Lee, Stephen Tan',450000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Concepcion, Fe Lardizabal',350000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Pangulayan, Luis Meinrado Calano',300000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Policarpio, Rufino III Llamas',300000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Yap, Ronald F.',300000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Dizon, Abaraham',200000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Uy, Danilo Co',200000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Uy, Wilfredo Co',200000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Alabanza, Terence Jonathan Lim',150000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Burkley, Alben Paguirigan',150000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Cheng, Michael Steven Go',150000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Santos, Alma Gracia Jo',150000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Sim, Johann',120000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Asi, Allan Rolando A.',100000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Cheng, Euegen Sim',100000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Desamito, Julio Regino Jr. Idos',100000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Sim, Annabelle Lim',100000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Tagum, Andrei Bon C.',100000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('Sia, Annalisa Lim',50000,'Cash');
INSERT INTO VPEscudero_campaigndonors VALUES ('TOTAL',99670000,NULL);
