CREATE TABLE VPTrillanes_campaigndonors (
    CAMPAIGN_CONTRIBUTORS VARCHAR(33) CHARACTER SET utf8,
    AMOUNT INT,
    TYPE_OF_DONATION VARCHAR(28) CHARACTER SET utf8
);
INSERT INTO VPTrillanes_campaigndonors VALUES ('Marcos, Donato Dionisio',3000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Trillanes, Henry Iriola',3000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Robles, Reynaldo Bustos',1090000,'cash and media advertisement');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Aquino-Ebol, Lady Klarenn',1000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Gabriel, Conrado C.',1000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Gabriel, Presentacion B.',1000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Guevarra, Argee',1000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Leytte, Thelma',1000000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Cristobal, Samuel Lozada',600000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Averilla, Rolando Tanabe',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Barleta, Pio Armando',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Emlano, Arsenia M.',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Fong, Robert Go',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Mindanao, Teresita',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Orejana, Joveniano',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Rellosa, Hector',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Tolentino, Gerardo',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Torrato, Andy',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Trillanes, Antonio Jr. Fuentes',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Uy, Ronald Allan',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Villapando, Nieves',500000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Chua, Charlie',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Diso, Ronald Edades',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Gonzales, Eugene',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Lintongan, Samsudin Tambilingan',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Lo, Norman Spencer Binsted Oya-Oy',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Macarubbo, Jeveeboy Narag',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Monteverde, Lily',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Nayve, Abner',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Orfiano, Jasmin',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Orongan, Christopher Prado',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Pontejos, Armand',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Rull, Filmore Gimenez',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Santiago, Norberto Estimada',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Santos, Micheal',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Tamba, Cezar Carmel Tanaguiton',300000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Alejano, Alfred',250000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Cojuangco, Levinia',250000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Sealey, Susie',250000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Alejano, Angelica',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Antonio, Ami Kritine',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Arce, Jose Jr.',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Cañero, Nena Patricio',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Dimaculangan, Estrella',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Espeleta, Ronald',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Ford, Lorenza Luna',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Gonzales, Florida',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Mr. and Mrs. Alimagno Rolando',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Pancho, Restituto Salazar',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Pascua, Arturo Jr. Salcedo',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Patawaran, Aries Garcia',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Ramos, Luzviminda Buquing',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Rull, Dominador',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Sangalang, Jonell Preagula',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Tayab, Von Rio Padsico',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Tocloy, Audie Solano',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Tolentino, Earl Derrick Tamani',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Valiente, Giovanni',200000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Brucal, Vivencio P.',175000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Jaldon, Micheal',175000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Cambel, Marybeth',160000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Cabochan, Myla B.',150000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Consejo, Jessie',150000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Jardinero, Monalisa V.',150000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Manomat, Christine C.',150000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Urdabe, Carlos',150000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Averilla, Richard Tanabe',100000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Ilao, Gaudencio Jr.',100000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Punzalan, Hipolito',100000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Reyes, Juan Marcos',100000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Tamani, Carmelita B.',100000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Maniquiz, Roselle',50000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('Go, Augusto Wong',30000,'Cash');
INSERT INTO VPTrillanes_campaigndonors VALUES ('TOTAL',29580000,NULL);
